### ISSUE TITLE
Error when uploading pfp

### ISSUE THREAD

**Issue by JohnSiegel** [PhitNest/phitnest#121]
This error occurred when uploading a pfp on the mobile app:

![Screenshot 2023-12-22 110003](https://github.com/PhitNest/phitnest/assets/36650083/56d4a5f6-b086-42be-903d-0204a868f49f)

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI
file:///data/user/0/com.phitnest.android/cache/image_cropper_1703260739795.jpg

When the exception was thrown, this was the stack:
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2752:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2628:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:104:59)
#3      NetworkImage.loadImage (package:flutter/src/painting/_network_image_io.dart:66:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:520:39)
#5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:377:22)
#6      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:517:81)
#7      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:104:19)
#8      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:366:9)
#9      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:479:24)
#10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43:39)
#11     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:476:9)
#12     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:363:5)
#13     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1110:16)
#14     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1060:5)
#15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5629:11)
#16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456:5)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#18     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#19     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905:32)
...     Normal element mounting (9 frames)
#28     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (23 frames)
#51     _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#58     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#65     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (123 frames)
#188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#189    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#190    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905:32)
...     Normal element mounting (134 frames)
#324    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#325    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#326    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6905:32)
...     Normal element mounting (178 frames)
#504    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335:16)
#505    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6893:36)
#506    Element.updateChild (package:flutter/src/widgets/framework.dart:3846:18)
#507    Element.updateChildren (package:flutter/src/widgets/framework.dart:4033:32)
#508    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#509    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#510    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#511    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#512    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#513    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#514    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#515    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#516    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#517    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#518    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#519    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#520    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#521    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#522    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#523    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#524    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#525    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#526    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#527    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#528    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#529    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#530    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#531    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#532    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#533    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#534    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#535    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#536    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#537    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#538    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#539    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#540    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#541    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#542    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#543    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#544    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#545    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#546    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#547    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#548    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#549    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#550    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#551    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#552    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#553    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#554    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#555    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#556    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#557    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#558    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#559    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#560    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#561    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#562    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#563    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#564    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#565    _invoke (dart:ui/hooks.dart:312:13)
#566    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:382:5)
#567    _drawFrame (dart:ui/hooks.dart:283:31)

Image provider:
  NetworkImage("/data/user/0/com.phitnest.android/cache/image_cropper_1703260739795.jpg", scale:
  1.0)
Image key: NetworkImage("/data/user/0/com.phitnest.android/cache/image_cropper_1703260739795.jpg",
```

**Comment by JohnSiegel** [comment]
Fixed by reading image from file rather than network.
